// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdXIYJ9c623YTbSu1gZ0LsmD2IhcOZ7Xk',
    appId: '1:713831479275:web:c63370bf0ab3bf1774cbae',
    messagingSenderId: '713831479275',
    projectId: 'routeapp-8ea1d',
    authDomain: 'routeapp-8ea1d.firebaseapp.com',
    storageBucket: 'routeapp-8ea1d.appspot.com',
    measurementId: 'G-2T1034GHV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3MDnxy0Clu-mABcZLI3jJQ75EBBz5HQQ',
    appId: '1:713831479275:android:ab7ecb5dfbfb987274cbae',
    messagingSenderId: '713831479275',
    projectId: 'routeapp-8ea1d',
    storageBucket: 'routeapp-8ea1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB92mVwMyt78jhTV4qaQIU82HxpCt5J3A8',
    appId: '1:713831479275:ios:d269c763f24d173a74cbae',
    messagingSenderId: '713831479275',
    projectId: 'routeapp-8ea1d',
    storageBucket: 'routeapp-8ea1d.appspot.com',
    iosBundleId: 'com.example.taskroute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB92mVwMyt78jhTV4qaQIU82HxpCt5J3A8',
    appId: '1:713831479275:ios:3db4ac84b95681aa74cbae',
    messagingSenderId: '713831479275',
    projectId: 'routeapp-8ea1d',
    storageBucket: 'routeapp-8ea1d.appspot.com',
    iosBundleId: 'com.example.taskroute.RunnerTests',
  );
}
